var user = "sam"
console.log(user)

let num = 1000;
num = true;
console.log(num);

const dob= 1990;
dob = 2000;
console.log(dob);

var a =10;
var a =30;
console.log(a);

let b= 20;
console.log(b);


const c= True;
console.log(c);


 let s1 = "double quotes";
 console.log(s1);
 console.log(typeof(s1));

 let str2 = 'single quotes';
 console.log(str2);
 console.log(typeof(str2));

 let str3 = `template literals`;
 console.log(str3);
 console.log(typeof(str3));

 let numm = 10.345678;
 console.log(numm , typeof(numm));

 let bool = true;
 console.log(bool , typeof(bool));
